filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*
    - /games/*
  parsers:
    - multiline:
        type: pattern
        pattern: '^\d\d\d\d[-]'
        negate: true
        match: after


processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["nginx:5044"]